query IssueView($owner: String!, $name: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    issue(number: $number) {
      number
      url
      id
      title
      state
      body
      labels(first: 100) {
        pageInfo {
          hasNextPage
        }
        nodes {
          name
        }
      }
      assignees(first: 100) {
        pageInfo {
          hasNextPage
        }
        nodes {
          login
        }
      }
      author {
        login
      }
      createdAt
      updatedAt
      closedAt
    }
  }
}
